"""Insight dialog for common segments comparison.

Called by:
    - ``ui.main_window.MainWindow`` when showing segment analysis

Consumes:
    - Segment data produced by ``core.analyzer.find_common_segments``
    - Coach insights generated by ``core.analyzer.generate_segment_coach_insights``
"""

from PyQt6.QtCore import Qt, pyqtSignal, QEvent, QPoint
from PyQt6.QtGui import QColor, QBrush, QCursor
from PyQt6.QtWidgets import (
    QDialog,
    QVBoxLayout,
    QHBoxLayout,
    QTableWidget,
    QTableWidgetItem,
    QPushButton,
    QLabel,
    QHeaderView,
    QTextEdit,
    QSplitter,
    QWidget,
)
from core.analyzer import calculate_point_speed, haversine_distance


def _format_timestamp(timestamp):
    """Format a timestamp to HH:MM:SS or N/A."""
    if timestamp is None:
        return "N/A"
    try:
        return timestamp.strftime("%H:%M:%S")
    except Exception:
        return "N/A"


def _get_speed_kmh(point):
    """Return speed in km/h from a track point, or None."""
    speed = getattr(point, "speed", None)
    if isinstance(speed, (int, float)) and speed >= 0:
        return float(speed * 3.6)
    return None


def _format_duration(seconds):
    """Format a duration in seconds to MM:SS or HH:MM:SS."""
    if seconds is None:
        return "N/A"
    seconds = int(round(seconds))
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    secs = seconds % 60
    if hours > 0:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    return f"{minutes}:{secs:02d}"


def _format_pace(avg_speed_kmh):
    """Format average speed in km/h to min/km pace string."""
    if avg_speed_kmh is None or avg_speed_kmh <= 0:
        return "N/A"
    pace_min_per_km = 60.0 / avg_speed_kmh
    minutes = int(pace_min_per_km)
    seconds = int(round((pace_min_per_km - minutes) * 60))
    if seconds >= 60:
        minutes += 1
        seconds -= 60
    return f"{minutes}'{seconds:02d}\""


class InsightDialog(QDialog):
    """Dialog showing detailed comparison of common segments between two tracks."""
    segment_point_selected = pyqtSignal(str, int)

    def __init__(self, segments: list[dict], name_a: str = "Attività A", name_b: str = "Attività B", track_a=None, track_b=None, parent=None):
        """Create the insight dialog.

        Args:
            segments: List of common segment dictionaries.
            name_a: Display name for the first activity.
            name_b: Display name for the second activity.
            track_a: Original track for activity A.
            track_b: Original track for activity B.
            parent: Optional parent widget.
        """
        super().__init__(parent)
        self.setWindowTitle("Analisi Segmenti Comuni")
        self.setModal(True)
        self.resize(1100, 600)

        self.segments = segments
        self.name_a = name_a
        self.name_b = name_b
        self.track_a = track_a
        self.track_b = track_b

        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(12)

        total_length = sum(s["length_m"] for s in segments) / 1000.0 if segments else 0.0
        summary_text = (
            f"<b>Segmenti comuni trovati:</b> {len(segments)} | "
            f"<b>Distanza totale sovrapposta:</b> {total_length:.2f} km"
        )
        summary_label = QLabel(summary_text)
        summary_label.setWordWrap(True)
        layout.addWidget(summary_label)

        splitter = QSplitter(Qt.Orientation.Vertical)
        layout.addWidget(splitter, 1)

        self.table = QTableWidget()
        self.table.setColumnCount(11)
        self.table.setHorizontalHeaderLabels([
            "N.",
            "Traccia A (m)",
            "Traccia B (m)",
            "Distanza (m)",
            "Tempo A",
            "Tempo B",
            "Δ Tempo",
            "Ritmo A",
            "Ritmo B",
            "Δ Vel (km/h)",
            "Δ FC (bpm)",
        ])
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Fixed)
        self.table.setColumnWidth(0, 40)
        self.table.verticalHeader().setVisible(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.table.cellClicked.connect(self._on_segment_row_clicked)
        splitter.addWidget(self.table)

        coach_widget = QWidget()
        coach_layout = QVBoxLayout(coach_widget)
        coach_layout.setContentsMargins(0, 0, 0, 0)

        coach_title = QLabel("<b>Coach Insights</b>")
        coach_layout.addWidget(coach_title)

        self.coach_text = QTextEdit()
        self.coach_text.setReadOnly(True)
        coach_layout.addWidget(self.coach_text)

        splitter.addWidget(coach_widget)
        splitter.setSizes([400, 220])

        button_layout = QHBoxLayout()
        button_layout.addStretch(1)
        close_button = QPushButton("Chiudi")
        close_button.clicked.connect(self.accept)
        button_layout.addWidget(close_button)
        layout.addLayout(button_layout)

        self._populate_table()
        self._populate_coach_insights()

    def _populate_table(self):
        """Fill the table with segment comparison data."""
        self.table.setRowCount(len(self.segments))

        for row, seg in enumerate(self.segments):
            item_id = QTableWidgetItem(str(seg.get("id", row + 1)))
            item_id.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 0, item_id)

            a_start = seg.get("a_start_dist_m", 0)
            a_end = seg.get("a_end_dist_m", 0)
            item_a = QTableWidgetItem(f"{a_start:.0f} - {a_end:.0f}")
            item_a.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 1, item_a)

            b_start = seg.get("b_start_dist_m", 0)
            b_end = seg.get("b_end_dist_m", 0)
            item_b = QTableWidgetItem(f"{b_start:.0f} - {b_end:.0f}")
            item_b.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 2, item_b)

            length = seg.get("length_m", 0)
            item_len = QTableWidgetItem(f"{length:.0f}")
            item_len.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 3, item_len)

            time_a = seg.get("time_a_sec")
            item_time_a = QTableWidgetItem(_format_duration(time_a))
            item_time_a.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 4, item_time_a)

            time_b = seg.get("time_b_sec")
            item_time_b = QTableWidgetItem(_format_duration(time_b))
            item_time_b.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 5, item_time_b)

            if time_a is not None and time_b is not None:
                diff_time = time_b - time_a
                item_diff_time = QTableWidgetItem(f"{diff_time:+.0f}s")
                item_diff_time.setForeground(QBrush(QColor("#2ecc71" if diff_time < 0 else "#e74c3c")))
            else:
                item_diff_time = QTableWidgetItem("N/A")
            item_diff_time.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 6, item_diff_time)

            pace_a = _format_pace(seg.get("avg_speed_a"))
            item_pace_a = QTableWidgetItem(pace_a)
            item_pace_a.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 7, item_pace_a)

            pace_b = _format_pace(seg.get("avg_speed_b"))
            item_pace_b = QTableWidgetItem(pace_b)
            item_pace_b.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 8, item_pace_b)

            spd_a = seg.get("avg_speed_a")
            spd_b = seg.get("avg_speed_b")
            if spd_a is not None and spd_b is not None:
                diff = spd_b - spd_a
                item_spd = QTableWidgetItem(f"{diff:+.1f}")
                item_spd.setForeground(QBrush(QColor("#2ecc71" if diff > 0 else "#e74c3c")))
            else:
                item_spd = QTableWidgetItem("N/A")
            item_spd.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 9, item_spd)

            hr_a = seg.get("avg_hr_a")
            hr_b = seg.get("avg_hr_b")
            if hr_a is not None and hr_b is not None:
                diff = hr_b - hr_a
                item_hr = QTableWidgetItem(f"{diff:+.0f}")
                item_hr.setForeground(QBrush(QColor("#2ecc71" if diff < 0 else "#e74c3c")))
            else:
                item_hr = QTableWidgetItem("N/A")
            item_hr.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 10, item_hr)

    def _on_segment_row_clicked(self, row, column):
        if row < 0 or row >= len(self.segments):
            return
        segment = self.segments[row]
        dialog = SegmentDetailDialog(
            segment,
            self.track_a,
            self.track_b,
            self.name_a,
            self.name_b,
            parent=self,
        )
        dialog.point_selected.connect(self.segment_point_selected)
        dialog.exec()

    def _populate_coach_insights(self):
        """Import the coach insights generator from core.analyzer."""
        from core.analyzer import generate_segment_coach_insights

        insights = generate_segment_coach_insights(self.segments, self.name_a, self.name_b)
        self.coach_text.setHtml("<br>".join(insights))


class SegmentDetailDialog(QDialog):
    """Point-by-point comparison for a single common segment."""
    point_selected = pyqtSignal(str, int)

    def __init__(self, segment, track_a, track_b, name_a="Attività A", name_b="Attività B", parent=None):
        super().__init__(parent)
        self.setWindowTitle(f"Dettaglio Segmento {segment.get('id', '?')}")
        self.setModal(True)
        self.resize(1000, 600)

        self.segment = segment
        self.track_a = track_a
        self.track_b = track_b
        self.name_a = name_a
        self.name_b = name_b

        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(12)

        summary_text = (
            f"<b>Segmento {segment.get('id', '?')}</b> | "
            f"{name_a} vs {name_b} | "
            f"Distanza: {segment.get('length_m', 0):.0f} m"
        )
        summary_label = QLabel(summary_text)
        summary_label.setWordWrap(True)
        layout.addWidget(summary_label)

        self.table = QTableWidget()
        self.table.setColumnCount(9)
        self.table.setHorizontalHeaderLabels([
            "Bucket",
            "Tempo A",
            "Tempo B",
            "Δ Tempo",
            "Vel A (km/h)",
            "Vel B (km/h)",
            "Δ Vel (km/h)",
            "FC A (bpm)",
            "FC B (bpm)",
        ])
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Fixed)
        self.table.setColumnWidth(0, 80)
        self.table.verticalHeader().setVisible(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.table.cellClicked.connect(self._on_detail_cell_clicked)
        self.table.viewport().installEventFilter(self)
        layout.addWidget(self.table)

        splitter = QSplitter(Qt.Orientation.Vertical)
        splitter.addWidget(self.table)

        self.time_table = QTableWidget()
        self.time_table.setColumnCount(9)
        self.time_table.setHorizontalHeaderLabels([
            "Bucket",
            "Dist A (m)",
            "Dist B (m)",
            "Δ Dist (m)",
            "Vel A (km/h)",
            "Vel B (km/h)",
            "Δ Vel (km/h)",
            "FC A (bpm)",
            "FC B (bpm)",
        ])
        self.time_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.time_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Fixed)
        self.time_table.setColumnWidth(0, 80)
        self.time_table.verticalHeader().setVisible(False)
        self.time_table.setAlternatingRowColors(True)
        self.time_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.time_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.time_table.cellClicked.connect(self._on_time_cell_clicked)
        self.time_table.viewport().installEventFilter(self)
        splitter.addWidget(self.time_table)

        layout.addWidget(splitter)

        self._populate_points()
        self._populate_time_buckets()

    def _populate_time_buckets(self):
        a_start = self.segment.get("a_start_idx", 0)
        a_end = self.segment.get("a_end_idx", 0)
        b_start = self.segment.get("b_start_idx", 0)
        b_end = self.segment.get("b_end_idx", 0)

        points_a = self._points_a
        points_b = self._points_b

        start_ts_a = getattr(points_a[0], "timestamp", None) if points_a else None
        start_ts_b = getattr(points_b[0], "timestamp", None) if points_b else None

        bucket_seconds = 30.0
        max_time = 0.0
        if points_a and start_ts_a is not None:
            max_time = max(max_time, (points_a[-1].timestamp - start_ts_a).total_seconds())
        if points_b and start_ts_b is not None:
            max_time = max(max_time, (points_b[-1].timestamp - start_ts_b).total_seconds())

        num_buckets = int(max_time / bucket_seconds) + 1 if max_time > 0 else 0
        buckets = []
        for _ in range(num_buckets):
            buckets.append({
                "a_points": [],
                "b_points": [],
                "a_indices": [],
                "b_indices": [],
                "a_start_dist": 0.0,
                "b_start_dist": 0.0,
                "a_end_dist": 0.0,
                "b_end_dist": 0.0,
            })

        dists_a = self._dists_a if hasattr(self, "_dists_a") else [0.0]
        dists_b = self._dists_b if hasattr(self, "_dists_b") else [0.0]

        for i, p in enumerate(points_a):
            if start_ts_a is None or getattr(p, "timestamp", None) is None:
                continue
            rel = (p.timestamp - start_ts_a).total_seconds()
            b_idx = int(rel / bucket_seconds)
            if b_idx < num_buckets:
                if not buckets[b_idx]["a_points"]:
                    buckets[b_idx]["a_start_dist"] = dists_a[i]
                    buckets[b_idx]["a_indices"].append(a_start + i)
                buckets[b_idx]["a_end_dist"] = dists_a[i]
                buckets[b_idx]["a_points"].append(p)
                buckets[b_idx]["a_indices"].append(a_start + i)

        for i, p in enumerate(points_b):
            if start_ts_b is None or getattr(p, "timestamp", None) is None:
                continue
            rel = (p.timestamp - start_ts_b).total_seconds()
            b_idx = int(rel / bucket_seconds)
            if b_idx < num_buckets:
                if not buckets[b_idx]["b_points"]:
                    buckets[b_idx]["b_start_dist"] = dists_b[i]
                    buckets[b_idx]["b_indices"].append(b_start + i)
                buckets[b_idx]["b_end_dist"] = dists_b[i]
                buckets[b_idx]["b_points"].append(p)
                buckets[b_idx]["b_indices"].append(b_start + i)

        self.time_table.setRowCount(num_buckets)

        self._time_rep_points_a = []
        self._time_rep_points_b = []
        self._time_rep_starts_a = []
        self._time_rep_starts_b = []

        for b_idx, bucket in enumerate(buckets):
            start_t = b_idx * bucket_seconds
            end_t = (b_idx + 1) * bucket_seconds
            item_num = QTableWidgetItem(f"{_format_duration(start_t)} – {_format_duration(end_t)}")
            item_num.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            item_num.setToolTip("Mostra il bucket su entrambe le attività")
            self.time_table.setItem(b_idx, 0, item_num)

            if bucket["a_points"]:
                mid_idx = len(bucket["a_points"]) // 2
                rep_a = bucket["a_points"][mid_idx]
                rep_a_idx = bucket["a_indices"][mid_idx]
                dist_a = self._dists_a[rep_a_idx - a_start] if rep_a_idx - a_start < len(self._dists_a) else 0.0
            else:
                rep_a = None
                rep_a_idx = a_start
                dist_a = 0.0

            self._time_rep_points_a.append(rep_a)
            self._time_rep_starts_a.append(rep_a_idx)
            item_da = QTableWidgetItem(f"{dist_a:.0f}")
            item_da.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 1, item_da)

            if bucket["b_points"]:
                mid_idx = len(bucket["b_points"]) // 2
                rep_b = bucket["b_points"][mid_idx]
                rep_b_idx = bucket["b_indices"][mid_idx]
                dist_b = self._dists_b[rep_b_idx - b_start] if rep_b_idx - b_start < len(self._dists_b) else 0.0
            else:
                rep_b = None
                rep_b_idx = b_start
                dist_b = 0.0

            self._time_rep_points_b.append(rep_b)
            self._time_rep_starts_b.append(rep_b_idx)
            item_db = QTableWidgetItem(f"{dist_b:.0f}")
            item_db.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 2, item_db)

            delta = dist_b - dist_a if dist_b is not None and dist_a is not None else None
            item_delta = QTableWidgetItem(f"{delta:+.0f}" if delta is not None else "N/A")
            item_delta.setForeground(QBrush(QColor("#2ecc71" if delta is not None and delta >= 0 else "#e74c3c")))
            item_delta.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 3, item_delta)

            speeds_a = []
            for idx in bucket["a_indices"]:
                if idx > a_start and idx - a_start - 1 < len(points_a):
                    spd = calculate_point_speed(points_a[idx - a_start - 1], points_a[idx - a_start])
                    if spd is not None:
                        speeds_a.append(spd)
            avg_speed_a = sum(speeds_a) / len(speeds_a) if speeds_a else None
            item_sa = QTableWidgetItem(f"{avg_speed_a:.1f}" if avg_speed_a is not None else "N/A")
            item_sa.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 4, item_sa)

            speeds_b = []
            for idx in bucket["b_indices"]:
                if idx > b_start and idx - b_start - 1 < len(points_b):
                    spd = calculate_point_speed(points_b[idx - b_start - 1], points_b[idx - b_start])
                    if spd is not None:
                        speeds_b.append(spd)
            avg_speed_b = sum(speeds_b) / len(speeds_b) if speeds_b else None
            item_sb = QTableWidgetItem(f"{avg_speed_b:.1f}" if avg_speed_b is not None else "N/A")
            item_sb.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 5, item_sb)

            hrs_a = [getattr(p, "heart_rate", None) for p in bucket["a_points"] if getattr(p, "heart_rate", None) is not None]
            avg_hr_a = sum(hrs_a) / len(hrs_a) if hrs_a else None
            item_ha = QTableWidgetItem(str(int(round(avg_hr_a))) if avg_hr_a is not None else "N/A")
            item_ha.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 7, item_ha)

            hrs_b = [getattr(p, "heart_rate", None) for p in bucket["b_points"] if getattr(p, "heart_rate", None) is not None]
            avg_hr_b = sum(hrs_b) / len(hrs_b) if hrs_b else None
            item_hb = QTableWidgetItem(str(int(round(avg_hr_b))) if avg_hr_b is not None else "N/A")
            item_hb.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 8, item_hb)

            if avg_speed_a is not None and avg_speed_b is not None:
                diff = avg_speed_b - avg_speed_a
                item_ds = QTableWidgetItem(f"{diff:+.1f}")
                item_ds.setForeground(QBrush(QColor("#2ecc71" if diff > 0 else "#e74c3c")))
            else:
                item_ds = QTableWidgetItem("N/A")
            item_ds.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 6, item_ds)

    def _on_time_cell_clicked(self, row, column):
        if row < 0 or row >= len(self._time_rep_points_a):
            return

        if self._time_rep_points_a[row] is not None:
            self.point_selected.emit("A", self._time_rep_starts_a[row])

        if self._time_rep_points_b[row] is not None:
            self.point_selected.emit("B", self._time_rep_starts_b[row])

    def eventFilter(self, obj, event):
        if obj is self.table.viewport() or obj is self.time_table.viewport():
            if event.type() == QEvent.Type.MouseMove:
                table = self.table if obj is self.table.viewport() else self.time_table
                pos = event.pos()
                index = table.indexAt(pos)
                if index.column() == 0:
                    table.viewport().setCursor(Qt.CursorShape.PointingHandCursor)
                else:
                    table.viewport().setCursor(Qt.CursorShape.ArrowCursor)
            elif event.type() == QEvent.Type.Leave:
                if obj is self.table.viewport():
                    self.table.viewport().setCursor(Qt.CursorShape.ArrowCursor)
                else:
                    self.time_table.viewport().setCursor(Qt.CursorShape.ArrowCursor)
        return super().eventFilter(obj, event)

    def _populate_points(self):
        a_start = self.segment.get("a_start_idx", 0)
        a_end = self.segment.get("a_end_idx", 0)
        b_start = self.segment.get("b_start_idx", 0)
        b_end = self.segment.get("b_end_idx", 0)

        points_a = self.track_a.points[a_start:a_end + 1] if self.track_a else []
        points_b = self.track_b.points[b_start:b_end + 1] if self.track_b else []

        self._points_a = points_a
        self._points_b = points_b
        self._a_start = a_start
        self._b_start = b_start

        start_ts_a = getattr(points_a[0], "timestamp", None) if points_a else None
        start_ts_b = getattr(points_b[0], "timestamp", None) if points_b else None

        dists_a = [0.0]
        for i in range(1, len(points_a)):
            dists_a.append(dists_a[-1] + haversine_distance(points_a[i-1], points_a[i]))

        dists_b = [0.0]
        for i in range(1, len(points_b)):
            dists_b.append(dists_b[-1] + haversine_distance(points_b[i-1], points_b[i]))

        bucket_size = 50.0
        max_dist = max(dists_a[-1] if dists_a else 0.0, dists_b[-1] if dists_b else 0.0)
        num_buckets = int(max_dist / bucket_size) + 1 if max_dist > 0 else 0

        buckets = []
        for _ in range(num_buckets):
            buckets.append({
                "a_points": [],
                "b_points": [],
                "a_indices": [],
                "b_indices": [],
            })

        for i, d in enumerate(dists_a):
            b_idx = int(d / bucket_size)
            if b_idx < num_buckets:
                buckets[b_idx]["a_points"].append(points_a[i])
                buckets[b_idx]["a_indices"].append(a_start + i)

        for i, d in enumerate(dists_b):
            b_idx = int(d / bucket_size)
            if b_idx < num_buckets:
                buckets[b_idx]["b_points"].append(points_b[i])
                buckets[b_idx]["b_indices"].append(b_start + i)

        self.table.setRowCount(num_buckets)

        self._rep_points_a = []
        self._rep_points_b = []
        self._rep_starts_a = []
        self._rep_starts_b = []

        self._dists_a = dists_a
        self._dists_b = dists_b

        for b_idx, bucket in enumerate(buckets):
            start_dist = b_idx * bucket_size
            end_dist = (b_idx + 1) * bucket_size
            item_num = QTableWidgetItem(f"{start_dist:.0f}–{end_dist:.0f} m")
            item_num.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            item_num.setToolTip("Mostra il bucket su entrambe le attività")
            self.table.setItem(b_idx, 0, item_num)

            if bucket["a_points"]:
                mid_idx = len(bucket["a_points"]) // 2
                rep_a = bucket["a_points"][mid_idx]
                rep_a_idx = bucket["a_indices"][mid_idx]
            else:
                rep_a = None
                rep_a_idx = a_start

            self._rep_points_a.append(rep_a)
            self._rep_starts_a.append(rep_a_idx)

            if bucket["b_points"]:
                mid_idx = len(bucket["b_points"]) // 2
                rep_b = bucket["b_points"][mid_idx]
                rep_b_idx = bucket["b_indices"][mid_idx]
            else:
                rep_b = None
                rep_b_idx = b_start

            self._rep_points_b.append(rep_b)
            self._rep_starts_b.append(rep_b_idx)

            if rep_a and getattr(rep_a, "timestamp", None) is not None and start_ts_a is not None:
                rel_a = (rep_a.timestamp - start_ts_a).total_seconds()
                item_ta = QTableWidgetItem(_format_duration(rel_a))
            else:
                item_ta = QTableWidgetItem("N/A")
            item_ta.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(b_idx, 1, item_ta)

            if rep_b and getattr(rep_b, "timestamp", None) is not None and start_ts_b is not None:
                rel_b = (rep_b.timestamp - start_ts_b).total_seconds()
                item_tb = QTableWidgetItem(_format_duration(rel_b))
            else:
                item_tb = QTableWidgetItem("N/A")
            item_tb.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(b_idx, 2, item_tb)

            speeds_a = []
            for idx in bucket["a_indices"]:
                if idx > a_start and idx - a_start - 1 < len(points_a):
                    spd = calculate_point_speed(points_a[idx - a_start - 1], points_a[idx - a_start])
                    if spd is not None:
                        speeds_a.append(spd)
            avg_speed_a = sum(speeds_a) / len(speeds_a) if speeds_a else None
            item_sa = QTableWidgetItem(f"{avg_speed_a:.1f}" if avg_speed_a is not None else "N/A")
            item_sa.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            speeds_b = []
            for idx in bucket["b_indices"]:
                if idx > b_start and idx - b_start - 1 < len(points_b):
                    spd = calculate_point_speed(points_b[idx - b_start - 1], points_b[idx - b_start])
                    if spd is not None:
                        speeds_b.append(spd)
            avg_speed_b = sum(speeds_b) / len(speeds_b) if speeds_b else None
            item_sb = QTableWidgetItem(f"{avg_speed_b:.1f}" if avg_speed_b is not None else "N/A")
            item_sb.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            hrs_a = [getattr(p, "heart_rate", None) for p in bucket["a_points"] if getattr(p, "heart_rate", None) is not None]
            avg_hr_a = sum(hrs_a) / len(hrs_a) if hrs_a else None
            item_ha = QTableWidgetItem(str(int(round(avg_hr_a))) if avg_hr_a is not None else "N/A")
            item_ha.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            hrs_b = [getattr(p, "heart_rate", None) for p in bucket["b_points"] if getattr(p, "heart_rate", None) is not None]
            avg_hr_b = sum(hrs_b) / len(hrs_b) if hrs_b else None
            item_hb = QTableWidgetItem(str(int(round(avg_hr_b))) if avg_hr_b is not None else "N/A")
            item_hb.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            if rep_a and rep_b and getattr(rep_a, "timestamp", None) is not None and getattr(rep_b, "timestamp", None) is not None and start_ts_a is not None and start_ts_b is not None:
                rel_a = (rep_a.timestamp - start_ts_a).total_seconds()
                rel_b = (rep_b.timestamp - start_ts_b).total_seconds()
                diff = rel_b - rel_a
                item_dt = QTableWidgetItem(f"{diff:+.0f}s")
                item_dt.setForeground(QBrush(QColor("#2ecc71" if diff < 0 else "#e74c3c")))
            else:
                item_dt = QTableWidgetItem("N/A")
            item_dt.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            if avg_speed_a is not None and avg_speed_b is not None:
                diff = avg_speed_b - avg_speed_a
                item_ds = QTableWidgetItem(f"{diff:+.1f}")
                item_ds.setForeground(QBrush(QColor("#2ecc71" if diff > 0 else "#e74c3c")))
            else:
                item_ds = QTableWidgetItem("N/A")
            item_ds.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            self.table.setItem(b_idx, 3, item_dt)
            self.table.setItem(b_idx, 4, item_sa)
            self.table.setItem(b_idx, 5, item_sb)
            self.table.setItem(b_idx, 6, item_ds)
            self.table.setItem(b_idx, 7, item_ha)
            self.table.setItem(b_idx, 8, item_hb)

    def _on_detail_cell_clicked(self, row, column):
        if row < 0 or row >= len(self._rep_points_a):
            return

        if self._rep_points_a[row] is not None:
            self.point_selected.emit("A", self._rep_starts_a[row])

        if self._rep_points_b[row] is not None:
            self.point_selected.emit("B", self._rep_starts_b[row])