"""Insight dialog for common segments comparison.

Called by:
    - ``ui.main_window.MainWindow`` when showing segment analysis

Consumes:
    - Segment data produced by ``core.analyzer.find_common_segments``
    - Coach insights generated by ``core.analyzer.generate_segment_coach_insights``
    - AI report generated by ``core.ai_agent`` (Ollama locale, opzionale)
"""

import json
import logging
import os

from PyQt6.QtCore import (
    QEvent,
    QObject,
    QPoint,
    QRunnable,
    QThreadPool,
    QTime,
    Qt,
    pyqtSignal,
    pyqtSlot,
)
from PyQt6.QtGui import QBrush, QColor, QCursor
from PyQt6.QtWidgets import (
    QComboBox,
    QDialog,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QMessageBox,
    QPushButton,
    QSpinBox,
    QSplitter,
    QTableWidget,
    QTableWidgetItem,
    QTextEdit,
    QTimeEdit,
    QVBoxLayout,
    QWidget,
)
from core.analyzer import calculate_point_speed, haversine_distance
from core.ai_agent import (
    DEFAULT_BASE_URL,
    DEFAULT_MODEL,
    KNOWN_LOCAL_MODELS,
    OllamaUnavailableError,
    build_comparison_snapshot,
    generate_ai_comparison,
    generate_offline_fallback_report,
    list_local_models,
    run_agentic_comparison,
)

log = logging.getLogger(__name__)


def _format_timestamp(timestamp):
    """Format a timestamp to HH:MM:SS or N/A."""
    if timestamp is None:
        return "N/A"
    try:
        return timestamp.strftime("%H:%M:%S")
    except Exception:
        return "N/A"


def _get_speed_kmh(point):
    """Return speed in km/h from a track point, or None."""
    speed = getattr(point, "speed", None)
    if isinstance(speed, (int, float)) and speed >= 0:
        return float(speed * 3.6)
    return None


def _format_duration(seconds, decimals=0):
    """Format a duration in seconds to MM:SS or HH:MM:SS, with optional decimals."""
    if seconds is None:
        return "N/A"
    total = float(seconds)
    hours = int(total) // 3600
    minutes = (int(total) % 3600) // 60
    if decimals and decimals > 0:
        secs = total % 60
        fmt = f"{{:0{2 + decimals + 1}.{decimals}f}}"
        if hours > 0:
            return f"{hours}:{minutes:02d}:{fmt.format(secs)}"
        return f"{minutes}:{fmt.format(secs)}"
    secs = int(total) % 60
    if hours > 0:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    return f"{minutes}:{secs:02d}"


def _format_pace(avg_speed_kmh):
    """Format average speed in km/h to min/km pace string."""
    if avg_speed_kmh is None or avg_speed_kmh <= 0:
        return "N/A"
    pace_min_per_km = 60.0 / avg_speed_kmh
    minutes = int(pace_min_per_km)
    seconds = int(round((pace_min_per_km - minutes) * 60))
    if seconds >= 60:
        minutes += 1
        seconds -= 60
    return f"{minutes}'{seconds:02d}\""


def _get_track_duration(track):
    """Calcola la durata in secondi di una traccia (dal primo all'ultimo punto)."""
    if not track or not hasattr(track, 'points') or not track.points:
        return None
    first_ts = getattr(track.points[0], 'timestamp', None)
    last_ts = getattr(track.points[-1], 'timestamp', None)
    if first_ts and last_ts:
        try:
            return (last_ts - first_ts).total_seconds()
        except Exception:
            return None
    return None


class _WorkerKeeper:
    """Mantiene vivi i riferimenti Python dei worker finché non completano.

    ``QThreadPool`` detiene solo il riferimento C++ del QRunnable: se il
    wrapper Python (e con esso l'oggetto dei segnali) viene raccolto dal GC
    mentre il thread è ancora in esecuzione, la successiva ``emit`` crasha
    con "wrapped C/C++ object has been deleted".
    """

    _instances = set()

    @classmethod
    def track(cls, worker: QRunnable) -> None:
        """Registra un worker come in esecuzione."""
        cls._instances.add(worker)

    @classmethod
    def release(cls, worker: QRunnable) -> None:
        """Rilascia il worker a lavoro ultimato."""
        cls._instances.discard(worker)


class _WorkerSignals(QObject):
    """Segnali scambiati tra i thread di lavoro e la GUI."""

    # (kind, text) con kind in {"ai", "offline", "error"}
    finished = pyqtSignal(str, str)
    models_loaded = pyqtSignal(list)


class _AIAnalysisWorker(QRunnable):
    """Esegue la generazione del report IA fuori dal thread della GUI."""

    def __init__(self, snapshot, name_a, name_b, segments, model, base_url, timeout=1800.0):
        super().__init__()
        self.signals = _WorkerSignals()
        self._snapshot = snapshot
        self._name_a = name_a
        self._name_b = name_b
        self._segments = segments
        self._model = model
        self._base_url = base_url
        self._timeout = timeout

    @pyqtSlot()
    def run(self):
        try:
            report = generate_ai_comparison(
                self._snapshot,
                self._name_a,
                self._name_b,
                model=self._model,
                base_url=self._base_url,
                timeout=self._timeout,
            )
            self.signals.finished.emit("ai", report)
        except OllamaUnavailableError as exc:
            fallback = generate_offline_fallback_report(
                self._segments, self._name_a, self._name_b, str(exc)
            )
            self.signals.finished.emit("offline", fallback)
        except Exception as exc:  # noqa: BLE001
            log.exception("Analisi IA fallita inaspettatamente")
            self.signals.finished.emit("error", str(exc))


class _AIAgentWorker(QRunnable):
    """Esegue il loop agentico di tool-calling fuori dal thread della GUI."""

    def __init__(self, snapshot, name_a, name_b, segments, model, base_url,
                 on_highlight=None, timeout=1800.0):
        super().__init__()
        self.signals = _WorkerSignals()
        self._snapshot = snapshot
        self._name_a = name_a
        self._name_b = name_b
        self._segments = segments
        self._model = model
        self._base_url = base_url
        self._on_highlight = on_highlight
        self._timeout = timeout

    @pyqtSlot()
    def run(self):
        try:
            report, transcript = run_agentic_comparison(
                self._snapshot,
                self._name_a,
                self._name_b,
                self._segments,
                model=self._model,
                base_url=self._base_url,
                timeout=self._timeout,
                on_highlight=self._on_highlight,
            )
            if transcript:
                steps = "\n".join(
                    f"- `{step['tool']}` {json.dumps(step['args'], ensure_ascii=False, default=str)}"
                    for step in transcript
                )
                report = f"{report}\n\n---\n**Strumenti usati dall'agente:**\n{steps}"
            self.signals.finished.emit("ai", report)
        except OllamaUnavailableError as exc:
            fallback = generate_offline_fallback_report(
                self._segments, self._name_a, self._name_b, str(exc)
            )
            self.signals.finished.emit("offline", fallback)
        except Exception as exc:  # noqa: BLE001
            log.exception("Agente IA fallito inaspettatamente")
            self.signals.finished.emit("error", str(exc))


class _OllamaModelsWorker(QRunnable):
    """Recupera i modelli locali disponibili senza bloccare la GUI."""

    def __init__(self, base_url, timeout=3.0):
        super().__init__()
        self.signals = _WorkerSignals()
        self._base_url = base_url
        self._timeout = timeout

    @pyqtSlot()
    def run(self):
        try:
            models = list_local_models(self._base_url, timeout=self._timeout)
        except OllamaUnavailableError:
            models = []
        self.signals.models_loaded.emit(models)


class InsightDialog(QDialog):
    """Dialog showing detailed comparison of common segments between two tracks."""
    segment_point_selected = pyqtSignal(str, int)

    def __init__(self, segments: list[dict], name_a: str = "Attività A", name_b: str = "Attività B", track_a=None, track_b=None, parent=None):
        """Create the insight dialog.

        Args:
            segments: List of common segment dictionaries.
            name_a: Display name for the first activity.
            name_b: Display name for the second activity.
            track_a: Original track for activity A.
            track_b: Original track for activity B.
            parent: Optional parent widget.
        """
        super().__init__(parent)
        self.setWindowTitle("Analisi Segmenti Comuni")
        self.setModal(False)
        self.resize(1100, 600)

        self.segments = segments
        self.name_a = name_a
        self.name_b = name_b
        self.track_a = track_a
        self.track_b = track_b

        # DEBUG: Stampa tutti i dati delle due tracce
        print("\n" + "="*80)
        print("DEBUG INSIGHT DIALOG - DATI TRACCE")
        print("="*80)
        print(f"Name A: {name_a}")
        print(f"Name B: {name_b}")
        print(f"\nTrack A: {track_a}")
        print(f"Track B: {track_b}")
        
        if track_a:
            print(f"\nTrack A - Numero punti: {len(track_a.points) if hasattr(track_a, 'points') else 'N/A'}")
            if hasattr(track_a, 'points') and track_a.points:
                print(f"Track A - Primo punto: {track_a.points[0]}")
                print(f"Track A - Ultimo punto: {track_a.points[-1]}")
                if hasattr(track_a.points[0], 'timestamp'):
                    print(f"Track A - Timestamp inizio: {track_a.points[0].timestamp}")
                    print(f"Track A - Timestamp fine: {track_a.points[-1].timestamp}")
        
        if track_b:
            print(f"\nTrack B - Numero punti: {len(track_b.points) if hasattr(track_b, 'points') else 'N/A'}")
            if hasattr(track_b, 'points') and track_b.points:
                print(f"Track B - Primo punto: {track_b.points[0]}")
                print(f"Track B - Ultimo punto: {track_b.points[-1]}")
                if hasattr(track_b.points[0], 'timestamp'):
                    print(f"Track B - Timestamp inizio: {track_b.points[0].timestamp}")
                    print(f"Track B - Timestamp fine: {track_b.points[-1].timestamp}")
        
        print(f"\nNumero segmenti: {len(segments)}")
        print("\nDettaglio segmenti:")
        for idx, seg in enumerate(segments):
            print(f"\n--- Segmento {idx + 1} ---")
            for key, value in seg.items():
                if key in ['coords_a', 'coords_b']:
                    print(f"  {key}: [{len(value)} coordinate]")
                elif key in ['resampled_points_a', 'resampled_points_b']:
                    print(f"  {key}: [{len(value) if value else 0} punti ricampionati]")
                else:
                    print(f"  {key}: {value}")
        print("="*80 + "\n")

        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(12)

        total_length = sum(s["length_m"] for s in segments) / 1000.0 if segments else 0.0
        summary_text = (
            f"<b>Segmenti comuni trovati:</b> {len(segments)} | "
            f"<b>Distanza totale sovrapposta:</b> {total_length:.2f} km"
        )
        summary_label = QLabel(summary_text)
        summary_label.setWordWrap(True)
        layout.addWidget(summary_label)

        splitter = QSplitter(Qt.Orientation.Vertical)
        layout.addWidget(splitter, 1)

        self.table = QTableWidget()
        self.table.setColumnCount(11)
        self.table.setHorizontalHeaderLabels([
            "N.",
            "Traccia A (m)",
            "Traccia B (m)",
            "Distanza (m)",
            "Tempo A",
            "Tempo B",
            "Δ Tempo",
            "Ritmo A",
            "Ritmo B",
            "Δ Vel (km/h)",
            "Δ FC (bpm)",
        ])
        # Abilita il ridimensionamento manuale delle colonne
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        self.table.setColumnWidth(0, 40)
        self.table.verticalHeader().setVisible(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.table.cellClicked.connect(self._on_segment_row_clicked)
        splitter.addWidget(self.table)

        coach_widget = QWidget()
        coach_layout = QVBoxLayout(coach_widget)
        coach_layout.setContentsMargins(0, 0, 0, 0)

        coach_title = QLabel("<b>Coach Insights</b>")
        coach_layout.addWidget(coach_title)

        self.coach_text = QTextEdit()
        self.coach_text.setReadOnly(True)
        coach_layout.addWidget(self.coach_text)

        splitter.addWidget(coach_widget)

        ai_widget = QWidget()
        ai_layout = QVBoxLayout(ai_widget)
        ai_layout.setContentsMargins(0, 0, 0, 0)

        ai_title = QLabel("<b>Analisi IA (Ollama)</b>")
        ai_layout.addWidget(ai_title)

        ai_controls = QHBoxLayout()
        self.ai_button = QPushButton("✨ Analisi IA")
        self.ai_button.setToolTip(
            "Genera un report in linguaggio naturale confrontando le due tracce "
            "tramite un LLM locale (richiede Ollama in esecuzione)."
        )
        self.ai_button.clicked.connect(self._on_ai_analysis_clicked)
        ai_controls.addWidget(self.ai_button, 0)

        self.ai_agent_button = QPushButton("🤖 Agente")
        self.ai_agent_button.setToolTip(
            "Esegue il loop agentico: può interrogare i dati dettagliati "
            "(velocità max, FC max, dislivello) e portare la mappa su un "
            "segmento prima di scrivere il report."
        )
        self.ai_agent_button.clicked.connect(self._on_ai_agent_clicked)
        ai_controls.addWidget(self.ai_agent_button, 0)

        ai_controls.addWidget(QLabel("Modello:"))
        self.ai_model_combo = QComboBox()
        self.ai_model_combo.setEditable(True)
        self.ai_model_combo.setMinimumWidth(140)
        for model in KNOWN_LOCAL_MODELS:
            self.ai_model_combo.addItem(model)
        default_model = os.environ.get("DUOTRACK_OLLAMA_MODEL", DEFAULT_MODEL)
        default_idx = self.ai_model_combo.findText(default_model)
        if default_idx >= 0:
            self.ai_model_combo.setCurrentIndex(default_idx)
        else:
            self.ai_model_combo.setEditText(default_model)
        ai_controls.addWidget(self.ai_model_combo, 1)

        self.ai_status_label = QLabel("")
        self.ai_status_label.setStyleSheet("color: #8a8a8a;")
        ai_controls.addWidget(self.ai_status_label, 0)
        ai_layout.addLayout(ai_controls)

        self.ai_text = QTextEdit()
        self.ai_text.setReadOnly(True)
        self.ai_text.setPlaceholderText(
            'Premi "✨ Analisi IA" per un report conversazionale del confronto,\n'
            'oppure "🤖 Agente" per l\'analisi agentica con tool-calling.\n'
            "Richiede Ollama in esecuzione (es. `ollama pull qwen2.5:7b`).\n"
            "Se Ollama non è disponibile verrà mostrata l'analisi offline del Coach."
        )
        ai_layout.addWidget(self.ai_text)

        splitter.addWidget(ai_widget)
        splitter.setSizes([400, 200, 200])

        # Carica l'elenco dei modelli locali senza bloccare la finestra.
        models_worker = _OllamaModelsWorker(
            os.environ.get("DUOTRACK_OLLAMA_URL", DEFAULT_BASE_URL)
        )
        models_worker.signals.models_loaded.connect(self._on_models_loaded)
        models_worker.signals.models_loaded.connect(
            lambda *_args, w=models_worker: _WorkerKeeper.release(w)
        )
        _WorkerKeeper.track(models_worker)
        QThreadPool.globalInstance().start(models_worker)

        button_layout = QHBoxLayout()
        button_layout.addStretch(1)
        close_button = QPushButton("Chiudi")
        close_button.clicked.connect(self.accept)
        button_layout.addWidget(close_button)
        layout.addLayout(button_layout)

        self._populate_table()
        self._populate_coach_insights()

    def _populate_table(self):
        """Fill the table with segment comparison data."""
        self.table.setRowCount(len(self.segments))

        for row, seg in enumerate(self.segments):
            item_id = QTableWidgetItem(str(seg.get("id", row + 1)))
            item_id.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 0, item_id)

            a_start = seg.get("a_start_dist_m", 0)
            a_end = seg.get("a_end_dist_m", 0)
            item_a = QTableWidgetItem(f"{a_start:.0f} - {a_end:.0f}")
            item_a.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 1, item_a)

            b_start = seg.get("b_start_dist_m", 0)
            b_end = seg.get("b_end_dist_m", 0)
            item_b = QTableWidgetItem(f"{b_start:.0f} - {b_end:.0f}")
            item_b.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 2, item_b)

            length = seg.get("length_m", 0)
            item_len = QTableWidgetItem(f"{length:.0f}")
            item_len.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 3, item_len)

            time_a = seg.get("time_a_sec")
            item_time_a = QTableWidgetItem(_format_duration(time_a))
            item_time_a.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 4, item_time_a)

            time_b = seg.get("time_b_sec")
            item_time_b = QTableWidgetItem(_format_duration(time_b))
            item_time_b.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 5, item_time_b)

            if time_a is not None and time_b is not None:
                diff_time = time_b - time_a
                item_diff_time = QTableWidgetItem(f"{diff_time:+.0f}s")
                item_diff_time.setForeground(QBrush(QColor("#2ecc71" if diff_time < 0 else "#e74c3c")))
            else:
                item_diff_time = QTableWidgetItem("N/A")
            item_diff_time.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 6, item_diff_time)

            pace_a = _format_pace(seg.get("avg_speed_a"))
            item_pace_a = QTableWidgetItem(pace_a)
            item_pace_a.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 7, item_pace_a)

            pace_b = _format_pace(seg.get("avg_speed_b"))
            item_pace_b = QTableWidgetItem(pace_b)
            item_pace_b.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 8, item_pace_b)

            spd_a = seg.get("avg_speed_a")
            spd_b = seg.get("avg_speed_b")
            if spd_a is not None and spd_b is not None:
                diff = spd_b - spd_a
                item_spd = QTableWidgetItem(f"{diff:+.1f}")
                item_spd.setForeground(QBrush(QColor("#2ecc71" if diff > 0 else "#e74c3c")))
            else:
                item_spd = QTableWidgetItem("N/A")
            item_spd.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 9, item_spd)

            hr_a = seg.get("avg_hr_a")
            hr_b = seg.get("avg_hr_b")
            if hr_a is not None and hr_b is not None:
                diff = hr_b - hr_a
                item_hr = QTableWidgetItem(f"{diff:+.0f}")
                item_hr.setForeground(QBrush(QColor("#2ecc71" if diff < 0 else "#e74c3c")))
            else:
                item_hr = QTableWidgetItem("N/A")
            item_hr.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 10, item_hr)

    def _on_segment_row_clicked(self, row, column):
        if row < 0 or row >= len(self.segments):
            return
        segment = self.segments[row]
        dialog = SegmentDetailDialog(
            segment,
            self.track_a,
            self.track_b,
            self.name_a,
            self.name_b,
            parent=self,
        )
        dialog.point_selected.connect(self.segment_point_selected)
        dialog.show()

    def _populate_coach_insights(self):
        """Import the coach insights generator from core.analyzer."""
        from core.analyzer import generate_segment_coach_insights

        insights = generate_segment_coach_insights(self.segments, self.name_a, self.name_b)
        self.coach_text.setHtml("<br>".join(insights))

    # ------------------------------------------------------------- Analisi IA

    def _on_ai_analysis_clicked(self):
        """Avvia l'analisi IA in background tramite Ollama."""
        if not self.segments:
            QMessageBox.information(
                self, "Analisi IA", "Nessun segmento comune da analizzare."
            )
            return
        if self.track_a is None or self.track_b is None:
            QMessageBox.information(
                self,
                "Analisi IA",
                "Servono entrambe le tracce caricate per costruire il confronto.",
            )
            return

        model = self.ai_model_combo.currentText().strip()
        if not model:
            model = DEFAULT_MODEL
        base_url = os.environ.get("DUOTRACK_OLLAMA_URL", DEFAULT_BASE_URL)

        try:
            snapshot = build_comparison_snapshot(self.track_a, self.track_b, self.segments)
        except Exception as exc:  # noqa: BLE001
            QMessageBox.warning(
                self, "Analisi IA", f"Impossibile preparare i dati di confronto: {exc}"
            )
            return

        self.ai_button.setEnabled(False)
        self.ai_status_label.setText("Analisi in corso… (10–60 s)")
        self.ai_text.setPlainText("")

        worker = _AIAnalysisWorker(
            snapshot,
            self.name_a,
            self.name_b,
            self.segments,
            model,
            base_url,
            timeout=1800.0,
        )
        worker.signals.finished.connect(self._on_ai_finished)
        worker.signals.finished.connect(
            lambda *_args, w=worker: _WorkerKeeper.release(w)
        )
        _WorkerKeeper.track(worker)
        QThreadPool.globalInstance().start(worker)

    def _on_ai_agent_clicked(self):
        """Avvia il loop agentico (tool-calling) via Ollama in background."""
        if not self.segments:
            QMessageBox.information(
                self, "Agente IA", "Nessun segmento comune da analizzare."
            )
            return
        if self.track_a is None or self.track_b is None:
            QMessageBox.information(
                self,
                "Agente IA",
                "Servono entrambe le tracce caricate per costruire il confronto.",
            )
            return

        model = self.ai_model_combo.currentText().strip() or DEFAULT_MODEL
        base_url = os.environ.get("DUOTRACK_OLLAMA_URL", DEFAULT_BASE_URL)

        try:
            snapshot = build_comparison_snapshot(self.track_a, self.track_b, self.segments)
        except Exception as exc:  # noqa: BLE001
            QMessageBox.warning(
                self, "Agente IA", f"Impossibile preparare i dati di confronto: {exc}"
            )
            return

        on_highlight = None
        parent = self.parent()
        if parent is not None and hasattr(parent, "focus_on_segment"):
            on_highlight = lambda seg_id, side, mw=parent: mw.focus_on_segment(seg_id, side)

        self.ai_button.setEnabled(False)
        self.ai_agent_button.setEnabled(False)
        self.ai_status_label.setText("Agente in esecuzione… (30–90 s)")
        self.ai_text.setPlainText("")

        worker = _AIAgentWorker(
            snapshot,
            self.name_a,
            self.name_b,
            self.segments,
            model,
            base_url,
            on_highlight=on_highlight,
            timeout=1800.0,
        )
        worker.signals.finished.connect(self._on_ai_finished)
        worker.signals.finished.connect(
            lambda *_args, w=worker: _WorkerKeeper.release(w)
        )
        _WorkerKeeper.track(worker)
        QThreadPool.globalInstance().start(worker)

    def _on_ai_finished(self, kind: str, text: str):
        """Gestisce l'esito del worker di analisi IA o dell'agente."""
        self.ai_button.setEnabled(True)
        if hasattr(self, "ai_agent_button"):
            self.ai_agent_button.setEnabled(True)
        if kind == "ai":
            self.ai_status_label.setText("")
            if hasattr(self.ai_text, "setMarkdown"):
                self.ai_text.setMarkdown(text)
            else:
                self.ai_text.setPlainText(text)
        elif kind == "offline":
            self.ai_status_label.setText("Ollama non raggiungibile — analisi offline")
            self.ai_text.setPlainText(text)
        else:
            self.ai_status_label.setText("Errore")
            QMessageBox.warning(
                self,
                "Analisi IA",
                f"Errore durante l'analisi:\n{text}\n\n"
                "Verifica che Ollama sia avviato e che il modello sia scaricato "
                "(`ollama pull qwen2.5:7b`).",
            )

    def _on_models_loaded(self, models):
        """Aggiorna la combo dei modelli con quelli realmente installati."""
        if not models:
            return
        current = self.ai_model_combo.currentText()
        self.ai_model_combo.clear()
        for model in models:
            self.ai_model_combo.addItem(model)
        if current:
            self.ai_model_combo.setCurrentText(current)
        else:
            default_idx = self.ai_model_combo.findText(DEFAULT_MODEL)
            if default_idx >= 0:
                self.ai_model_combo.setCurrentIndex(default_idx)


class SegmentDetailDialog(QDialog):
    """Point-by-point comparison for a single common segment."""
    point_selected = pyqtSignal(str, int)

    def __init__(self, segment, track_a, track_b, name_a="Attività A", name_b="Attività B", parent=None):
        super().__init__(parent)
        self.setWindowTitle(f"Dettaglio Segmento {segment.get('id', '?')}")
        self.setModal(False)
        self.resize(1000, 600)

        self.segment = segment
        self.track_a = track_a
        self.track_b = track_b
        self.name_a = name_a
        self.name_b = name_b

        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(12)

        duration_a = segment.get('time_a_sec')
        duration_b = segment.get('time_b_sec')

        summary_text = (
            f"<b>Segmento {segment.get('id', '?')}</b> | "
            f"{name_a} vs {name_b} | "
            f"Distanza: {segment.get('length_m', 0):.0f} m"
        )
        if duration_a is not None or duration_b is not None:
            dur_a_str = _format_duration(duration_a) if duration_a is not None else "N/A"
            dur_b_str = _format_duration(duration_b) if duration_b is not None else "N/A"
            summary_text += f" | Durata {name_a}: {dur_a_str} | Durata {name_b}: {dur_b_str}"
        summary_label = QLabel(summary_text)
        summary_label.setWordWrap(True)
        layout.addWidget(summary_label)

        # Controlli per la dimensione dei bucket
        controls_layout = QHBoxLayout()
        
        controls_layout.addWidget(QLabel("Bucket Distanza (m):"))
        self.dist_bucket_spin = QSpinBox()
        self.dist_bucket_spin.setRange(5, 1000)
        self.dist_bucket_spin.setValue(50)
        self.dist_bucket_spin.setSuffix(" m")
        self.dist_bucket_spin.valueChanged.connect(self._on_dist_bucket_changed)
        controls_layout.addWidget(self.dist_bucket_spin)
        
        controls_layout.addSpacing(20)
        
        controls_layout.addWidget(QLabel("Bucket Tempo:"))
        self.time_bucket_edit = QTimeEdit()
        self.time_bucket_edit.setDisplayFormat("HH:mm:ss")
        self.time_bucket_edit.setTime(QTime(0, 0, 30))
        self.time_bucket_edit.setMinimumTime(QTime(0, 0, 1))
        self.time_bucket_edit.timeChanged.connect(self._on_time_bucket_changed)
        controls_layout.addWidget(self.time_bucket_edit)
        
        controls_layout.addStretch()
        layout.addLayout(controls_layout)

        self.table = QTableWidget()
        self.table.setColumnCount(10)
        self.table.setHorizontalHeaderLabels([
            "Bucket",
            "Tempo A",
            "Tempo B",
            "Δ Tempo",
            "Tempo Compl A",
            "Tempo Compl B",
            "Δ Tempo Compl",
            "Vel A (km/h)",
            "Vel B (km/h)",
            "Δ Vel (km/h)",
        ])
        # Abilita il ridimensionamento manuale delle colonne
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        self.table.setColumnWidth(0, 80)
        self.table.verticalHeader().setVisible(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.table.cellClicked.connect(self._on_detail_cell_clicked)
        self.table.viewport().installEventFilter(self)
        layout.addWidget(self.table)

        splitter = QSplitter(Qt.Orientation.Vertical)
        splitter.addWidget(self.table)

        self.time_table = QTableWidget()
        self.time_table.setColumnCount(10)
        self.time_table.setHorizontalHeaderLabels([
            "Bucket",
            "Dist A (m)",
            "Dist B (m)",
            "Δ Dist (m)",
            "Dist Coperta A (m)",
            "Dist Coperta B (m)",
            "Δ Dist Coperta (m)",
            "Vel A (km/h)",
            "Vel B (km/h)",
            "Δ Vel (km/h)",
        ])
        # Abilita il ridimensionamento manuale delle colonne
        self.time_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
        self.time_table.setColumnWidth(0, 80)
        self.time_table.verticalHeader().setVisible(False)
        self.time_table.setAlternatingRowColors(True)
        self.time_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.time_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.time_table.cellClicked.connect(self._on_time_cell_clicked)
        self.time_table.viewport().installEventFilter(self)
        splitter.addWidget(self.time_table)

        layout.addWidget(splitter)

        self._prepare_data()
        self._update_distance_table()
        self._update_time_table()

    def _on_dist_bucket_changed(self):
        self._update_distance_table()

    def _on_time_bucket_changed(self):
        self._update_time_table()

    def _prepare_data(self):
        """Prepara i dati di base necessari per il calcolo dei bucket."""
        a_start = self.segment.get("a_start_idx", 0)
        a_end = self.segment.get("a_end_idx", 0)
        b_start = self.segment.get("b_start_idx", 0)
        b_end = self.segment.get("b_end_idx", 0)

        resampled_a = self.segment.get("resampled_points_a")
        resampled_b = self.segment.get("resampled_points_b")
        resampled_indices_a = self.segment.get("resampled_indices_a")
        resampled_indices_b = self.segment.get("resampled_indices_b")

        if resampled_a is not None:
            points_a = resampled_a
            indices_a = resampled_indices_a if resampled_indices_a else list(range(len(resampled_a)))
        else:
            points_a = self.track_a.points[a_start:a_end + 1] if self.track_a else []
            indices_a = [a_start + i for i in range(len(points_a))]

        if resampled_b is not None:
            points_b = resampled_b
            indices_b = resampled_indices_b if resampled_indices_b else list(range(len(resampled_b)))
        else:
            points_b = self.track_b.points[b_start:b_end + 1] if self.track_b else []
            indices_b = [b_start + i for i in range(len(points_b))]

        self._points_a = points_a
        self._points_b = points_b
        self._indices_a = indices_a
        self._indices_b = indices_b
        self._a_start = a_start
        self._b_start = b_start

        self._dists_a = [0.0]
        for i in range(1, len(points_a)):
            self._dists_a.append(self._dists_a[-1] + haversine_distance(points_a[i-1], points_a[i]))

        self._dists_b = [0.0]
        for i in range(1, len(points_b)):
            self._dists_b.append(self._dists_b[-1] + haversine_distance(points_b[i-1], points_b[i]))

    def _interpolate_dist_at_seconds(self, points, dists, target_seconds, start_ts):
        """Interpola la distanza cumulativa (in metri) al momento esatto `target_seconds`
        dall'inizio, lineare tra i due campioni che 'attraversano' quell'istante."""
        if start_ts is None or not points or target_seconds <= 0:
            return None
        for i in range(1, len(points)):
            t0 = getattr(points[i - 1], "timestamp", None)
            t1 = getattr(points[i], "timestamp", None)
            if t0 is None or t1 is None:
                continue
            s0 = (t0 - start_ts).total_seconds()
            s1 = (t1 - start_ts).total_seconds()
            if s1 >= target_seconds:
                if s1 <= s0:
                    return None
                frac = (target_seconds - s0) / (s1 - s0)
                d0, d1 = dists[i - 1], dists[i]
                return d0 + (d1 - d0) * frac
        return None

    def _update_time_table(self):
        points_a = self._points_a
        points_b = self._points_b
        a_start = self._a_start
        b_start = self._b_start

        start_ts_a = getattr(points_a[0], "timestamp", None) if points_a else None
        start_ts_b = getattr(points_b[0], "timestamp", None) if points_b else None

        t = self.time_bucket_edit.time()
        bucket_seconds = float(t.hour() * 3600 + t.minute() * 60 + t.second())
        if bucket_seconds <= 0:
            bucket_seconds = 1.0
        
        # Calcola i tempi di fine effettivi di entrambe le tracce
        end_secs_a = (points_a[-1].timestamp - start_ts_a).total_seconds() if points_a and start_ts_a else 0.0
        end_secs_b = (points_b[-1].timestamp - start_ts_b).total_seconds() if points_b and start_ts_b else 0.0
        
        min_end = min(end_secs_a, end_secs_b)
        max_end = max(end_secs_a, end_secs_b)

        # Costruisci i confini dei bucket:
        # - 30s regolari fino alla fine della traccia più lunga
        # - se la traccia più corta finisce a metà bucket, inserisci un confine aggiuntivo
        # - l'ultimo bucket finisce esattamente all'orario di fine della traccia più lunga
        bucket_boundaries = [0.0]
        t = bucket_seconds
        while t <= max_end:
            bucket_boundaries.append(t)
            t += bucket_seconds
        
        # Se min_end non è su un confine regolare, inseriscilo nella posizione corretta
        if min_end not in bucket_boundaries and min_end < max_end:
            inserted = False
            for i, b in enumerate(bucket_boundaries):
                if b > min_end:
                    bucket_boundaries.insert(i, min_end)
                    inserted = True
                    break
            # Se non è stato inserito (tutti i confini sono <= min_end), aggiungilo alla fine
            if not inserted:
                bucket_boundaries.append(min_end)
        
        # Rimuovi confini oltre max_end (con tolleranza per floating point)
        bucket_boundaries = [b for b in bucket_boundaries if b <= max_end + 0.001]
        
        # Assicurati che max_end sia l'ultimo confine
        if bucket_boundaries[-1] < max_end - 0.001:
            bucket_boundaries.append(max_end)
        
        # Rimuovi duplicati e ordina
        bucket_boundaries = sorted(list(set(bucket_boundaries)))

        num_buckets = len(bucket_boundaries) - 1
        buckets = []
        for b_idx in range(num_buckets):
            buckets.append({
                "a_points": [],
                "b_points": [],
                "a_indices": [],
                "b_indices": [],
                "a_start_dist": 0.0,
                "b_start_dist": 0.0,
                "a_end_dist": 0.0,
                "b_end_dist": 0.0,
                "a_last_point": None,
                "b_last_point": None,
                "a_last_index": None,
                "b_last_index": None,
                "start_time": bucket_boundaries[b_idx],
                "end_time": bucket_boundaries[b_idx + 1],
            })

        dists_a = self._dists_a if hasattr(self, "_dists_a") else [0.0]
        dists_b = self._dists_b if hasattr(self, "_dists_b") else [0.0]

        def find_bucket_idx(rel_time):
            """Trova l'indice del bucket per un dato tempo relativo."""
            for i in range(num_buckets):
                if bucket_boundaries[i] <= rel_time < bucket_boundaries[i + 1]:
                    return i
            # Se è esattamente al confine finale, mettilo nell'ultimo bucket
            return num_buckets - 1

        for i, p in enumerate(points_a):
            if start_ts_a is None or getattr(p, "timestamp", None) is None:
                continue
            rel = (p.timestamp - start_ts_a).total_seconds()
            b_idx = find_bucket_idx(rel)
            if b_idx < num_buckets:
                if not buckets[b_idx]["a_points"]:
                    buckets[b_idx]["a_start_dist"] = dists_a[i]
                    buckets[b_idx]["a_indices"].append(self._indices_a[i])
                buckets[b_idx]["a_end_dist"] = dists_a[i]
                buckets[b_idx]["a_points"].append(p)
                buckets[b_idx]["a_indices"].append(self._indices_a[i])
                buckets[b_idx]["a_last_point"] = p
                buckets[b_idx]["a_last_index"] = self._indices_a[i]

        for i, p in enumerate(points_b):
            if start_ts_b is None or getattr(p, "timestamp", None) is None:
                continue
            rel = (p.timestamp - start_ts_b).total_seconds()
            b_idx = find_bucket_idx(rel)
            if b_idx < num_buckets:
                if not buckets[b_idx]["b_points"]:
                    buckets[b_idx]["b_start_dist"] = dists_b[i]
                    buckets[b_idx]["b_indices"].append(self._indices_b[i])
                buckets[b_idx]["b_end_dist"] = dists_b[i]
                buckets[b_idx]["b_points"].append(p)
                buckets[b_idx]["b_indices"].append(self._indices_b[i])
                buckets[b_idx]["b_last_point"] = p
                buckets[b_idx]["b_last_index"] = self._indices_b[i]

        self.time_table.setRowCount(num_buckets)

        self._time_rep_points_a = []
        self._time_rep_points_b = []
        self._time_rep_starts_a = []
        self._time_rep_starts_b = []

        # DEBUG: Stampa tutti i dati dei bucket temporali
        print("\n" + "="*80)
        print(f"DEBUG INSIGHT DIALOG - BUCKET TEMPORALI ({bucket_seconds:.0f}s)")
        print("="*80)
        print(f"Numero bucket: {num_buckets}")
        print(f"Bucket boundaries: {bucket_boundaries}")
        print(f"End secs A: {end_secs_a:.2f}s")
        print(f"End secs B: {end_secs_b:.2f}s")
        print(f"\nDettaglio bucket:")
        for b_idx, bucket in enumerate(buckets):
            print(f"\n--- Bucket {b_idx + 1}/{num_buckets} ---")
            print(f"  Tempo: {bucket['start_time']:.2f}s - {bucket['end_time']:.2f}s")
            print(f"  Punti A: {len(bucket['a_points'])}")
            print(f"  Indici A: {bucket['a_indices']}")
            print(f"  Distanza A: {bucket['a_start_dist']:.2f}m - {bucket['a_end_dist']:.2f}m")
            print(f"  Punti B: {len(bucket['b_points'])}")
            print(f"  Indici B: {bucket['b_indices']}")
            print(f"  Distanza B: {bucket['b_start_dist']:.2f}m - {bucket['b_end_dist']:.2f}m")
        print("="*80 + "\n")

        # Distanza cumulativa (interpolata) raggiunta ESATTAMENTE alla fine di ogni
        # bucket temporale, così A e B sono confrontati sullo stesso istante
        # indipendentemente dal campionamento GPS.
        # I bucket hanno durata variabile: 30s regolari, ma l'ultimo bucket di ogni
        # traccia finisce esattamente al tempo di fine della traccia stessa.
        max_secs_a = (points_a[-1].timestamp - start_ts_a).total_seconds() if points_a and start_ts_a else 0.0
        max_secs_b = (points_b[-1].timestamp - start_ts_b).total_seconds() if points_b and start_ts_b else 0.0

        cum_dists_a = [
            None if bucket_boundaries[b_idx] >= max_secs_a
            else self._interpolate_dist_at_seconds(
                points_a, dists_a, min(bucket_boundaries[b_idx + 1], max_secs_a), start_ts_a
            )
            for b_idx in range(num_buckets)
        ]
        cum_dists_b = [
            None if bucket_boundaries[b_idx] >= max_secs_b
            else self._interpolate_dist_at_seconds(
                points_b, dists_b, min(bucket_boundaries[b_idx + 1], max_secs_b), start_ts_b
            )
            for b_idx in range(num_buckets)
        ]

        for b_idx, bucket in enumerate(buckets):
            start_t = bucket["start_time"]
            end_t = bucket["end_time"]
            item_num = QTableWidgetItem(f"{_format_duration(start_t)} – {_format_duration(end_t)}")
            item_num.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            item_num.setToolTip("Mostra il bucket su entrambe le attività")
            self.time_table.setItem(b_idx, 0, item_num)

            # --- Distanza cumulativa al confine ESATTO di ogni bucket temporale (interpolato) ---
            cum_dist_a = cum_dists_a[b_idx]
            cum_dist_b = cum_dists_b[b_idx]

            # Punto rappresentativo per il click (ultimo campione reale del bucket)
            if bucket["a_points"]:
                rep_a = bucket["a_last_point"]
                rep_a_idx = bucket["a_last_index"]
            else:
                rep_a = None
                rep_a_idx = a_start

            self._time_rep_points_a.append(rep_a)
            self._time_rep_starts_a.append(rep_a_idx)
            item_da = QTableWidgetItem(f"{cum_dist_a:.1f}" if cum_dist_a is not None else "N/A")
            item_da.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 1, item_da)

            if bucket["b_points"]:
                rep_b = bucket["b_last_point"]
                rep_b_idx = bucket["b_last_index"]
            else:
                rep_b = None
                rep_b_idx = b_start

            self._time_rep_points_b.append(rep_b)
            self._time_rep_starts_b.append(rep_b_idx)
            item_db = QTableWidgetItem(f"{cum_dist_b:.1f}" if cum_dist_b is not None else "N/A")
            item_db.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 2, item_db)

            delta = cum_dist_b - cum_dist_a if cum_dist_b is not None and cum_dist_a is not None else None
            item_delta = QTableWidgetItem(f"{delta:+.1f}" if delta is not None else "N/A")
            item_delta.setForeground(QBrush(QColor("#2ecc71" if delta is not None and delta >= 0 else "#e74c3c")))
            item_delta.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 3, item_delta)

            # --- Distanza coperta nel singolo bucket = confine corrente - confine precedente ---
            prev_dist_a = cum_dists_a[b_idx - 1] if b_idx > 0 and cum_dists_a[b_idx - 1] is not None else 0.0
            prev_dist_b = cum_dists_b[b_idx - 1] if b_idx > 0 and cum_dists_b[b_idx - 1] is not None else 0.0

            covered_a = cum_dist_a - prev_dist_a if cum_dist_a is not None and prev_dist_a is not None else None
            covered_b = cum_dist_b - prev_dist_b if cum_dist_b is not None and prev_dist_b is not None else None

            item_ca = QTableWidgetItem(f"{covered_a:.1f}" if covered_a is not None else "N/A")
            item_ca.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 4, item_ca)

            item_cb = QTableWidgetItem(f"{covered_b:.1f}" if covered_b is not None else "N/A")
            item_cb.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 5, item_cb)

            delta_c = covered_b - covered_a if covered_b is not None and covered_a is not None else None
            item_dc = QTableWidgetItem(f"{delta_c:+.1f}" if delta_c is not None else "N/A")
            item_dc.setForeground(QBrush(QColor("#2ecc71" if delta_c is not None and delta_c >= 0 else "#e74c3c")))
            item_dc.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 6, item_dc)

            # Velocità media = distanza percorsa nel bucket / durata effettiva del bucket
            avg_speed_a = None
            if covered_a is not None:
                bucket_end_time = min(bucket_boundaries[b_idx + 1], max_secs_a)
                bucket_duration = bucket_end_time - bucket_boundaries[b_idx]
                if bucket_duration > 0:
                    avg_speed_a = (covered_a / bucket_duration) * 3.6

            item_sa = QTableWidgetItem(f"{avg_speed_a:.1f}" if avg_speed_a is not None else "N/A")
            item_sa.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 7, item_sa)

            avg_speed_b = None
            if covered_b is not None:
                bucket_end_time = min(bucket_boundaries[b_idx + 1], max_secs_b)
                bucket_duration = bucket_end_time - bucket_boundaries[b_idx]
                if bucket_duration > 0:
                    avg_speed_b = (covered_b / bucket_duration) * 3.6

            item_sb = QTableWidgetItem(f"{avg_speed_b:.1f}" if avg_speed_b is not None else "N/A")
            item_sb.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 8, item_sb)

            if avg_speed_a is not None and avg_speed_b is not None:
                diff = avg_speed_b - avg_speed_a
                item_ds = QTableWidgetItem(f"{diff:+.1f}")
                item_ds.setForeground(QBrush(QColor("#2ecc71" if diff > 0 else "#e74c3c")))
            else:
                item_ds = QTableWidgetItem("N/A")
            item_ds.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.time_table.setItem(b_idx, 9, item_ds)

    def _on_time_cell_clicked(self, row, column):
        if row < 0 or row >= len(self._time_rep_points_a):
            return

        if self._time_rep_points_a[row] is not None:
            self.point_selected.emit("A", self._time_rep_starts_a[row])

        if self._time_rep_points_b[row] is not None:
            self.point_selected.emit("B", self._time_rep_starts_b[row])

    def eventFilter(self, obj, event):
        if obj is self.table.viewport() or obj is self.time_table.viewport():
            if event.type() == QEvent.Type.MouseMove:
                table = self.table if obj is self.table.viewport() else self.time_table
                pos = event.pos()
                index = table.indexAt(pos)
                if index.column() == 0:
                    table.viewport().setCursor(Qt.CursorShape.PointingHandCursor)
                else:
                    table.viewport().setCursor(Qt.CursorShape.ArrowCursor)
            elif event.type() == QEvent.Type.Leave:
                if obj is self.table.viewport():
                    self.table.viewport().setCursor(Qt.CursorShape.ArrowCursor)
                else:
                    self.time_table.viewport().setCursor(Qt.CursorShape.ArrowCursor)
        return super().eventFilter(obj, event)

    def _interpolate_seconds_at_dist(self, points, dists, target_dist, start_ts):
        """Interpola il tempo (in secondi dall'inizio) al punto esatto in cui la traccia
        raggiunge `target_dist` metri.

        Usa l'interpolazione lineare tra i due campioni GPS che 'attraversano' la distanza
        target, così A e B vengono confrontati esattamente sulla stessa distanza anche se
        il campionamento non ha un punto a quella distanza.
        """
        if start_ts is None or not points or target_dist <= 0:
            return None
        for i in range(1, len(dists)):
            if dists[i] >= target_dist:
                d0, d1 = dists[i - 1], dists[i]
                t0 = getattr(points[i - 1], "timestamp", None)
                t1 = getattr(points[i], "timestamp", None)
                if t0 is None or t1 is None or d1 <= d0:
                    return None
                frac = (target_dist - d0) / (d1 - d0)
                interp_ts = t0 + (t1 - t0) * frac
                return (interp_ts - start_ts).total_seconds()
        return None

    def _update_distance_table(self):
        points_a = self._points_a
        points_b = self._points_b
        a_start = self._a_start
        b_start = self._b_start
        dists_a = self._dists_a
        dists_b = self._dists_b

        start_ts_a = getattr(points_a[0], "timestamp", None) if points_a else None
        start_ts_b = getattr(points_b[0], "timestamp", None) if points_b else None

        bucket_size = float(self.dist_bucket_spin.value())
        max_dist_a = dists_a[-1] if dists_a else 0.0
        max_dist_b = dists_b[-1] if dists_b else 0.0
        # Fine comune: si confrontano solo le distanze coperte da ENTRAMBE le
        # tracce. Se una finisce prima dell'altra, per la più lunga viene
        # interpolato il punto equivalente alla stessa distanza della più corta.
        if max_dist_a > 0 and max_dist_b > 0:
            max_dist = min(max_dist_a, max_dist_b)
        else:
            max_dist = max(max_dist_a, max_dist_b)
        num_buckets = int(max_dist / bucket_size) + 1 if max_dist > 0 else 0

        buckets = []
        for _ in range(num_buckets):
            buckets.append({
                "a_points": [],
                "b_points": [],
                "a_indices": [],
                "b_indices": [],
                "a_first_point": None,
                "b_first_point": None,
                "a_first_index": None,
                "b_first_index": None,
                "a_last_point": None,
                "b_last_point": None,
                "a_last_index": None,
                "b_last_index": None,
            })

        for i, d in enumerate(dists_a):
            if d > max_dist:
                continue
            b_idx = int(d / bucket_size)
            if b_idx < num_buckets:
                if not buckets[b_idx]["a_points"]:
                    buckets[b_idx]["a_first_point"] = points_a[i]
                    buckets[b_idx]["a_first_index"] = self._indices_a[i]
                buckets[b_idx]["a_points"].append(points_a[i])
                buckets[b_idx]["a_indices"].append(self._indices_a[i])
                buckets[b_idx]["a_last_point"] = points_a[i]
                buckets[b_idx]["a_last_index"] = self._indices_a[i]

        for i, d in enumerate(dists_b):
            if d > max_dist:
                continue
            b_idx = int(d / bucket_size)
            if b_idx < num_buckets:
                if not buckets[b_idx]["b_points"]:
                    buckets[b_idx]["b_first_point"] = points_b[i]
                    buckets[b_idx]["b_first_index"] = self._indices_b[i]
                buckets[b_idx]["b_points"].append(points_b[i])
                buckets[b_idx]["b_indices"].append(self._indices_b[i])
                buckets[b_idx]["b_last_point"] = points_b[i]
                buckets[b_idx]["b_last_index"] = self._indices_b[i]

        self.table.setRowCount(num_buckets)

        self._rep_points_a = []
        self._rep_points_b = []
        self._rep_starts_a = []
        self._rep_starts_b = []

        self._dists_a = dists_a
        self._dists_b = dists_b

        # DEBUG: Stampa tutti i dati dei bucket di distanza
        print("\n" + "="*80)
        print(f"DEBUG INSIGHT DIALOG - BUCKET DISTANZA ({bucket_size:.0f}m)")
        print("="*80)
        print(f"Numero bucket: {num_buckets}")
        print(f"Bucket size: {bucket_size:.1f}m")
        print(f"Max distanza A: {max_dist_a:.2f}m")
        print(f"Max distanza B: {max_dist_b:.2f}m")
        print(f"Max dist (fine comune): {max_dist:.2f}m")
        print(f"\nDettaglio bucket:")
        for b_idx, bucket in enumerate(buckets):
            start_dist = b_idx * bucket_size
            end_dist = (b_idx + 1) * bucket_size
            if b_idx == num_buckets - 1:
                end_dist = max_dist
            print(f"\n--- Bucket {b_idx + 1}/{num_buckets} ---")
            print(f"  Distanza: {start_dist:.0f}m - {end_dist:.0f}m")
            print(f"  Punti A: {len(bucket['a_points'])}")
            print(f"  Indici A: {bucket['a_indices']}")
            print(f"  Primo punto A: {bucket['a_first_point']}")
            print(f"  Ultimo punto A: {bucket['a_last_point']}")
            print(f"  Punti B: {len(bucket['b_points'])}")
            print(f"  Indici B: {bucket['b_indices']}")
            print(f"  Primo punto B: {bucket['b_first_point']}")
            print(f"  Ultimo punto B: {bucket['b_last_point']}")
        print("="*80 + "\n")

        # Tempo (interpolato) per raggiungere ESATTAMENTE la fine di ogni bucket
        # (50 m, 100 m, ...), in modo che A e B siano confrontati sulla stessa
        # distanza indipendentemente dal campionamento GPS.
        # La fine comune `max_dist` viene usata per entrambe: se una traccia
        # termina prima dell'altra, per la più lunga viene interpolato il tempo
        # al punto equivalente (stessa distanza della traccia più corta).
        common_end = max_dist

        cum_ts_a = [
            None if k * bucket_size >= common_end
            else self._interpolate_seconds_at_dist(
                points_a, dists_a, min((k + 1) * bucket_size, common_end), start_ts_a
            )
            for k in range(num_buckets)
        ]
        cum_ts_b = [
            None if k * bucket_size >= common_end
            else self._interpolate_seconds_at_dist(
                points_b, dists_b, min((k + 1) * bucket_size, common_end), start_ts_b
            )
            for k in range(num_buckets)
        ]

        for b_idx, bucket in enumerate(buckets):
            start_dist = b_idx * bucket_size
            end_dist = (b_idx + 1) * bucket_size
            if b_idx == num_buckets - 1:
                end_dist = max_dist
            item_num = QTableWidgetItem(f"{start_dist:.0f}–{end_dist:.0f} m")
            item_num.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            item_num.setToolTip("Mostra il bucket su entrambe le attività")
            self.table.setItem(b_idx, 0, item_num)

            if bucket["a_points"]:
                rep_a = bucket["a_last_point"]
                rep_a_idx = bucket["a_last_index"]
            else:
                rep_a = None
                rep_a_idx = a_start

            self._rep_points_a.append(rep_a)
            self._rep_starts_a.append(rep_a_idx)

            if bucket["b_points"]:
                rep_b = bucket["b_last_point"]
                rep_b_idx = bucket["b_last_index"]
            else:
                rep_b = None
                rep_b_idx = b_start

            self._rep_points_b.append(rep_b)
            self._rep_starts_b.append(rep_b_idx)

            # --- Tempo cumulativo al confine ESATTO del bucket (interpolato) ---
            cum_a = cum_ts_a[b_idx]
            cum_b = cum_ts_b[b_idx]

            item_ta = QTableWidgetItem(_format_duration(cum_a, 1) if cum_a is not None else "N/A")
            item_ta.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(b_idx, 1, item_ta)

            item_tb = QTableWidgetItem(_format_duration(cum_b, 1) if cum_b is not None else "N/A")
            item_tb.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(b_idx, 2, item_tb)

            # Velocità media = distanza del bucket / tempo impiegato per percorrerlo
            avg_speed_a = None
            cum_a_val = cum_ts_a[b_idx]
            if cum_a_val is not None:
                time_start = 0.0
                if b_idx > 0:
                    prev = cum_ts_a[b_idx - 1]
                    if prev is not None:
                        time_start = float(prev)
                time_in_bucket = float(cum_a_val) - time_start
                dist_in_bucket = min((b_idx + 1) * bucket_size, common_end) - b_idx * bucket_size
                if time_in_bucket > 0:
                    avg_speed_a = (dist_in_bucket / time_in_bucket) * 3.6

            item_sa = QTableWidgetItem(f"{avg_speed_a:.1f}" if avg_speed_a is not None else "N/A")
            item_sa.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            avg_speed_b = None
            cum_b_val = cum_ts_b[b_idx]
            if cum_b_val is not None:
                time_start = 0.0
                if b_idx > 0:
                    prev = cum_ts_b[b_idx - 1]
                    if prev is not None:
                        time_start = float(prev)
                time_in_bucket = float(cum_b_val) - time_start
                dist_in_bucket = min((b_idx + 1) * bucket_size, common_end) - b_idx * bucket_size
                if time_in_bucket > 0:
                    avg_speed_b = (dist_in_bucket / time_in_bucket) * 3.6

            item_sb = QTableWidgetItem(f"{avg_speed_b:.1f}" if avg_speed_b is not None else "N/A")
            item_sb.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            if cum_a is not None and cum_b is not None:
                diff = cum_b - cum_a
                item_dt = QTableWidgetItem(f"{diff:+.1f}s")
                item_dt.setForeground(QBrush(QColor("#2ecc71" if diff < 0 else "#e74c3c")))
            else:
                item_dt = QTableWidgetItem("N/A")
            item_dt.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            if avg_speed_a is not None and avg_speed_b is not None:
                diff = avg_speed_b - avg_speed_a
                item_ds = QTableWidgetItem(f"{diff:+.1f}")
                item_ds.setForeground(QBrush(QColor("#2ecc71" if diff > 0 else "#e74c3c")))
            else:
                item_ds = QTableWidgetItem("N/A")
            item_ds.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            # --- Durata del singolo bucket = tempo al confine corrente - tempo al confine precedente ---
            prev_cum_a = cum_ts_a[b_idx - 1] if b_idx > 0 and cum_ts_a[b_idx - 1] is not None else 0.0
            prev_cum_b = cum_ts_b[b_idx - 1] if b_idx > 0 and cum_ts_b[b_idx - 1] is not None else 0.0

            dur_a = cum_a - prev_cum_a if cum_a is not None and prev_cum_a is not None else None
            dur_b = cum_b - prev_cum_b if cum_b is not None and prev_cum_b is not None else None

            item_ta_compl = QTableWidgetItem(_format_duration(dur_a, 1) if dur_a is not None else "N/A")
            item_ta_compl.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            item_tb_compl = QTableWidgetItem(_format_duration(dur_b, 1) if dur_b is not None else "N/A")
            item_tb_compl.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            if dur_a is not None and dur_b is not None:
                diff_compl = dur_b - dur_a
                item_dt_compl = QTableWidgetItem(f"{diff_compl:+.1f}s")
                item_dt_compl.setForeground(QBrush(QColor("#2ecc71" if diff_compl < 0 else "#e74c3c")))
            else:
                item_dt_compl = QTableWidgetItem("N/A")
            item_dt_compl.setTextAlignment(Qt.AlignmentFlag.AlignCenter)

            self.table.setItem(b_idx, 3, item_dt)
            self.table.setItem(b_idx, 4, item_ta_compl)
            self.table.setItem(b_idx, 5, item_tb_compl)
            self.table.setItem(b_idx, 6, item_dt_compl)
            self.table.setItem(b_idx, 7, item_sa)
            self.table.setItem(b_idx, 8, item_sb)
            self.table.setItem(b_idx, 9, item_ds)

    def _on_detail_cell_clicked(self, row, column):
        if row < 0 or row >= len(self._rep_points_a):
            return

        if self._rep_points_a[row] is not None:
            self.point_selected.emit("A", self._rep_starts_a[row])

        if self._rep_points_b[row] is not None:
            self.point_selected.emit("B", self._rep_starts_b[row])