"""Insight dialog for common segments comparison.

Called by:
    - ``ui.main_window.MainWindow`` when showing segment analysis

Consumes:
    - Segment data produced by ``core.analyzer.find_common_segments``
    - Coach insights generated by ``core.analyzer.generate_segment_coach_insights``
"""

from PyQt6.QtCore import Qt
from PyQt6.QtGui import QColor, QBrush
from PyQt6.QtWidgets import (
    QDialog,
    QVBoxLayout,
    QHBoxLayout,
    QTableWidget,
    QTableWidgetItem,
    QPushButton,
    QLabel,
    QHeaderView,
    QTextEdit,
    QSplitter,
    QWidget,
)


def _format_duration(seconds):
    """Format a duration in seconds to MM:SS or HH:MM:SS."""
    if seconds is None:
        return "N/A"
    seconds = int(round(seconds))
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    secs = seconds % 60
    if hours > 0:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    return f"{minutes}:{secs:02d}"


def _format_pace(avg_speed_kmh):
    """Format average speed in km/h to min/km pace string."""
    if avg_speed_kmh is None or avg_speed_kmh <= 0:
        return "N/A"
    pace_min_per_km = 60.0 / avg_speed_kmh
    minutes = int(pace_min_per_km)
    seconds = int(round((pace_min_per_km - minutes) * 60))
    if seconds >= 60:
        minutes += 1
        seconds -= 60
    return f"{minutes}'{seconds:02d}\""


class InsightDialog(QDialog):
    """Dialog showing detailed comparison of common segments between two tracks."""

    def __init__(self, segments: list[dict], name_a: str = "Attività A", name_b: str = "Attività B", parent=None):
        """Create the insight dialog.

        Args:
            segments: List of common segment dictionaries.
            name_a: Display name for the first activity.
            name_b: Display name for the second activity.
            parent: Optional parent widget.
        """
        super().__init__(parent)
        self.setWindowTitle("Analisi Segmenti Comuni")
        self.setModal(True)
        self.resize(1100, 600)

        self.segments = segments
        self.name_a = name_a
        self.name_b = name_b

        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(12)

        total_length = sum(s["length_m"] for s in segments) / 1000.0 if segments else 0.0
        summary_text = (
            f"<b>Segmenti comuni trovati:</b> {len(segments)} | "
            f"<b>Distanza totale sovrapposta:</b> {total_length:.2f} km"
        )
        summary_label = QLabel(summary_text)
        summary_label.setWordWrap(True)
        layout.addWidget(summary_label)

        splitter = QSplitter(Qt.Orientation.Vertical)
        layout.addWidget(splitter, 1)

        self.table = QTableWidget()
        self.table.setColumnCount(13)
        self.table.setHorizontalHeaderLabels([
            "N.",
            "Traccia A (m)",
            "Traccia B (m)",
            "Distanza (m)",
            "Tempo A",
            "Tempo B",
            "Δ Tempo",
            "Ritmo A",
            "Ritmo B",
            "Δ Vel (km/h)",
            "Δ Pendenza (%)",
            "Δ Altitudine (m)",
            "Δ FC (bpm)",
        ])
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Fixed)
        self.table.setColumnWidth(0, 40)
        self.table.verticalHeader().setVisible(False)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        splitter.addWidget(self.table)

        coach_widget = QWidget()
        coach_layout = QVBoxLayout(coach_widget)
        coach_layout.setContentsMargins(0, 0, 0, 0)

        coach_title = QLabel("<b>Coach Insights</b>")
        coach_layout.addWidget(coach_title)

        self.coach_text = QTextEdit()
        self.coach_text.setReadOnly(True)
        coach_layout.addWidget(self.coach_text)

        splitter.addWidget(coach_widget)
        splitter.setSizes([400, 220])

        button_layout = QHBoxLayout()
        button_layout.addStretch(1)
        close_button = QPushButton("Chiudi")
        close_button.clicked.connect(self.accept)
        button_layout.addWidget(close_button)
        layout.addLayout(button_layout)

        self._populate_table()
        self._populate_coach_insights()

    def _populate_table(self):
        """Fill the table with segment comparison data."""
        self.table.setRowCount(len(self.segments))

        for row, seg in enumerate(self.segments):
            item_id = QTableWidgetItem(str(seg.get("id", row + 1)))
            item_id.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 0, item_id)

            a_start = seg.get("a_start_dist_m", 0)
            a_end = seg.get("a_end_dist_m", 0)
            item_a = QTableWidgetItem(f"{a_start:.0f} - {a_end:.0f}")
            item_a.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 1, item_a)

            b_start = seg.get("b_start_dist_m", 0)
            b_end = seg.get("b_end_dist_m", 0)
            item_b = QTableWidgetItem(f"{b_start:.0f} - {b_end:.0f}")
            item_b.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 2, item_b)

            length = seg.get("length_m", 0)
            item_len = QTableWidgetItem(f"{length:.0f}")
            item_len.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 3, item_len)

            time_a = seg.get("time_a_sec")
            item_time_a = QTableWidgetItem(_format_duration(time_a))
            item_time_a.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 4, item_time_a)

            time_b = seg.get("time_b_sec")
            item_time_b = QTableWidgetItem(_format_duration(time_b))
            item_time_b.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 5, item_time_b)

            if time_a is not None and time_b is not None:
                diff_time = time_b - time_a
                item_diff_time = QTableWidgetItem(f"{diff_time:+.0f}s")
                item_diff_time.setForeground(QBrush(QColor("#2ecc71" if diff_time < 0 else "#e74c3c")))
            else:
                item_diff_time = QTableWidgetItem("N/A")
            item_diff_time.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 6, item_diff_time)

            pace_a = _format_pace(seg.get("avg_speed_a"))
            item_pace_a = QTableWidgetItem(pace_a)
            item_pace_a.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 7, item_pace_a)

            pace_b = _format_pace(seg.get("avg_speed_b"))
            item_pace_b = QTableWidgetItem(pace_b)
            item_pace_b.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 8, item_pace_b)

            spd_a = seg.get("avg_speed_a")
            spd_b = seg.get("avg_speed_b")
            if spd_a is not None and spd_b is not None:
                diff = spd_b - spd_a
                item_spd = QTableWidgetItem(f"{diff:+.1f}")
                item_spd.setForeground(QBrush(QColor("#2ecc71" if diff > 0 else "#e74c3c")))
            else:
                item_spd = QTableWidgetItem("N/A")
            item_spd.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 9, item_spd)

            slope_a = seg.get("slope_a")
            slope_b = seg.get("slope_b")
            if slope_a is not None and slope_b is not None:
                diff = slope_b - slope_a
                item_slope = QTableWidgetItem(f"{diff:+.1f}")
                item_slope.setForeground(QBrush(QColor("#2ecc71" if diff > 0 else "#e74c3c")))
            else:
                item_slope = QTableWidgetItem("N/A")
            item_slope.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 10, item_slope)

            alt_a = seg.get("avg_alt_a")
            alt_b = seg.get("avg_alt_b")
            if alt_a is not None and alt_b is not None:
                diff = alt_b - alt_a
                item_alt = QTableWidgetItem(f"{diff:+.0f}")
            else:
                item_alt = QTableWidgetItem("N/A")
            item_alt.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 11, item_alt)

            hr_a = seg.get("avg_hr_a")
            hr_b = seg.get("avg_hr_b")
            if hr_a is not None and hr_b is not None:
                diff = hr_b - hr_a
                item_hr = QTableWidgetItem(f"{diff:+.0f}")
                item_hr.setForeground(QBrush(QColor("#2ecc71" if diff < 0 else "#e74c3c")))
            else:
                item_hr = QTableWidgetItem("N/A")
            item_hr.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, 12, item_hr)

    def _populate_coach_insights(self):
        """Import the coach insights generator from core.analyzer."""
        from core.analyzer import generate_segment_coach_insights

        insights = generate_segment_coach_insights(self.segments, self.name_a, self.name_b)
        self.coach_text.setHtml("<br>".join(insights))